env:
  TERM: xterm-256color
window:
  padding:
    x: 20
    y: 20
  startup_mode: Windowed
  dynamic_title: true
  class:
    instance: Alacritty
    general: Alacritty
  gtk_theme_variant: None
scrolling:
  history: 10000
  multiplier: 3
font:
  normal:
    family: Iosevka Nerd Font
    style: Regular
  bold:
    family: Iosevka Nerd Font
    style: Bold
  italic:
    family: Iosevka Nerd Font
    style: Italic
  size: 16
scrolling:
  history: 10000
draw_bold_text_with_bright_colors: true
colors:
  name: Sex Colors
  author: ""
  primary:
    background: "#000000"
    foreground: "#ffffff"
  cursor:
    text: "#000000"
    cursor: "#ffffff"
  normal:
    black: "#252525"
    red: "#ff9f95"
    green: "#a6e22e"
    yellow: "#fd971f"
    blue: "#435e87"
    magenta: "#789ec6"
    cyan: "#5e7175"
    white: "#dbdcdc"
  bright:
    black: "#454545"
    red: "#ff8d80"
    green: "#b6e354"
    yellow: "#fd971f"
    blue: "#587aa4"
    magenta: "#46a4ff"
    cyan: "#a3babf"
    white: "#fdfdfd"
window.opacity: 0.5
selection:
  save_to_clipboard: false
live_config_reload: true
ig_reload: true
oad: true
_config_reload: true
yellow: "#8b7653"
blue: "#556b79"
magenta: "#6e4962"
cyan: "#5c8482"
white: "#828282"
hite: "#828282"
